// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWLib8qoXQI9HL3qs8me5eeDuZYItO7Xo',
    appId: '1:382409232438:web:387689a9899c1780c38897',
    messagingSenderId: '382409232438',
    projectId: 'biztrack-pbb-uas',
    authDomain: 'biztrack-pbb-uas.firebaseapp.com',
    storageBucket: 'biztrack-pbb-uas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEVG--Ftey3l635pVrjibb6AIwmZuS2JY',
    appId: '1:382409232438:android:3dd0fda697f5ea88c38897',
    messagingSenderId: '382409232438',
    projectId: 'biztrack-pbb-uas',
    storageBucket: 'biztrack-pbb-uas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhn4a4BussEs7tjFoGVX6q1-fwQsHwABs',
    appId: '1:382409232438:ios:d3536a174f339184c38897',
    messagingSenderId: '382409232438',
    projectId: 'biztrack-pbb-uas',
    storageBucket: 'biztrack-pbb-uas.firebasestorage.app',
    iosBundleId: 'com.example.biztrackPbb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhn4a4BussEs7tjFoGVX6q1-fwQsHwABs',
    appId: '1:382409232438:ios:d3536a174f339184c38897',
    messagingSenderId: '382409232438',
    projectId: 'biztrack-pbb-uas',
    storageBucket: 'biztrack-pbb-uas.firebasestorage.app',
    iosBundleId: 'com.example.biztrackPbb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWLib8qoXQI9HL3qs8me5eeDuZYItO7Xo',
    appId: '1:382409232438:web:f252a90a94c1e654c38897',
    messagingSenderId: '382409232438',
    projectId: 'biztrack-pbb-uas',
    authDomain: 'biztrack-pbb-uas.firebaseapp.com',
    storageBucket: 'biztrack-pbb-uas.firebasestorage.app',
  );
}
